#
# This file is part of the project tutteli/purchase published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/purchase
#

imports:
    - { resource: config_prod.yml }

assetic:
    read_from: "%kernel.root_dir%/../web/"

twig:
  globals:
    baseUrl:  /tutteli.ch/purchase/web/