#
# This file is part of the project tutteli/purchase published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/purchase
#
login:
    path:   /login{ending}
    defaults: { _controller: TutteliAppBundle:Security:login, ending: ""}

login_check:
    path:   /login_check
    defaults: { _controller: TutteliAppBundle:Security:loginCheck }    
    
logout:
    path: /logout
    
csrfToken:
    path: /login/token
    defaults: { _controller: TutteliAppBundle:Security:csrfToken }    

home:
    path:   /
    defaults: 
      _controller: FrameworkBundle:Redirect:redirect
      route:  purchase

purchase:
    path:   /purchase{ending}
    defaults: { _controller: TutteliAppBundle:Purchase:index, ending: ""}

purchase_new:
    path:   /purchase/new
    defaults: { _controller: TutteliAppBundle:Purchase:new}



admin_users:
    type: rest
    prefix: admin
    resource: Tutteli\AppBundle\Controller\UserController