#
# This file is part of the project tutteli/purchase published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/purchase
#

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    tutteli_auth_success_handler:
        class: Tutteli\AppBundle\Handler\AuthSuccessHandler
        arguments: ["@security.http_utils", {}]
        tags: 
          - {name: 'monolog.logger', channel: 'security' }
    tutteli_auth_failure_handler:
        class: Tutteli\AppBundle\Handler\AuthFailureHandler
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
