#
# This file is part of the project tutteli/puma published under the Apache License 2.0
# For the full copyright and license information, please have a look at LICENSE in the
# root folder or visit https://github.com/robstoll/PuMa
#

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    tutteli.auth_success_handler:
        class: Tutteli\AppBundle\Handler\AuthSuccessHandler
        arguments: ['%salt_key%', '@security.http_utils', {}]
        tags: 
          - {name: 'monolog.logger', channel: 'security' }
          
    tutteli.auth_failure_handler:
        class: Tutteli\AppBundle\Handler\AuthFailureHandler
        arguments: ['@http_kernel', '@security.http_utils', {}, '@logger', '@translator', '%kernel.environment%']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    tutteli.logout_success_handler:
        class: Tutteli\AppBundle\Handler\LogoutSuccessHandler
        arguments: ['@security.http_utils', 'REMEMBERME_A', '%baseUrl%']
        tags: 
          - {name: 'monolog.logger', channel: 'security' }
            
    app.exception_listener:
        class: Tutteli\AppBundle\Listener\ExceptionListener
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 50  }
            
    db.listeners.lastUpdated:
        class: Tutteli\AppBundle\Listener\DbLastUpdateListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    db.listeners.crypto:
        class: Tutteli\AppBundle\Listener\DbCryptoListener
        arguments: ['@session']
        tags: 
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }    
          - { name: doctrine.event_listener, event: postLoad }
          
    tutteli.csrf_service:
        class: Tutteli\AppBundle\Controller\CsrfService
        arguments: ['@security.csrf.token_manager']
        
    tutteli.json_service:
        class: Tutteli\AppBundle\Controller\JsonService
        arguments: ['@translator']
      
